### ISSUE TITLE
node versions in package.json not supported any longer

### ISSUE THREAD

**Issue by bcschaich** [SAP-samples/cloud-cf-multitenant-saas-provisioning-sample#2]
deployment of this project results in error as in package.json version 6.0 of node is used and obviously CP CF only supports versions higher than 8.  It worked after I changed all entries for 
`"node" : "6"`
to
`"node" : "8"`

Not sure if this is it...

**Comment by TerryHuang91** [comment]
After the deply the application, the application can not be opened on the provider subaccout. When I click on the link on the mt-hw-ar-app, it will redirect the a xs logon page which is not correct.
https://authentication.sap.hana.ondemand.com/login

**Comment by lmrigo** [comment]
I managed to make it work by removing the "engine" node from the package.json at the ap module.
I also had to add to the dependencies of both modules: "@sap/xsenv": "1.3.0"

**Comment by andrewlunde** [comment]
This is fixed.
