### ISSUE TITLE
 TENANT_HOST_PATTERN is not correct in the mta.yaml

### ISSUE THREAD

**Issue by TerryHuang91** [SAP-samples/cloud-cf-multitenant-saas-provisioning-sample#3]
Should be: 
TENANT_HOST_PATTERN: "^(.*)--mt-hw-ar-app.<Your CF Domain>"

**Comment by austinkloske22** [comment]
@doublezhuang can you explain the reason for the"--mt-hw-ar-app" change?

**Comment by andrewlunde** [comment]
Removed the landscape part of TENANT_HOST_PATTERN.
