### ISSUE TITLE
Unable to deploy to SCP 

### ISSUE THREAD

**Issue by TowkayNew** [SAP-samples/cloud-cf-multitenant-saas-provisioning-sample#5]
Attached is the build and deployment logs for your reference.
[cloud-cf-multitenant-saas-provisioning-sample.docx](https://github.com/SAP-samples/cloud-cf-multitenant-saas-provisioning-sample/files/4164354/cloud-cf-multitenant-saas-provisioning-sample.docx)

**Comment by Immanuelbh** [comment]
Having the same issue. Tried updating the various npm packages for each app, but still could not deploy.

**Comment by andrewlunde** [comment]
Tuned up.  Should build now.  Note <landscape> search/replace.
